name: Test docker image
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches: [ master ]

jobs:
  build:
    # Job name is Greeting
    name: Test image
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check current directory
        run: pwd

      - name: Change to new directory
        run: cd /usr/src/app

      - name: Check new directory
        run: pwd

      - name: Start container
        run: docker-compose -f docker-compose.ci.yml up -d --build

      - name: Check application availability
        run: curl 127.0.0.1:3000

      - name: Stop container
        run: docker-compose down
